# Generated by Django 5.0.4 on 2024-09-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_admin_options_alter_parent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
