# Generated by Django 5.0.4 on 2024-10-06 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_name', models.CharField(max_length=127, primary_key=True, serialize=False, unique=True)),
                ('homeroom_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_classes', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='SeatingPosition',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='seating_position', serialize=False, to='accounts.student')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_positions', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Seating Position',
                'verbose_name_plural': 'Seating Positions',
                'db_table': 'seating_position',
                'unique_together': {('room', 'row', 'column')},
            },
        ),
    ]
