# Generated by Django 5.0.4 on 2024-10-03 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=127, unique=True)),
                ('homeroom_teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='SeatingPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_positions', to='rooms.room')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seating_position', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Seating Position',
                'verbose_name_plural': 'Seating Positions',
                'db_table': 'seating_position',
                'unique_together': {('room', 'row', 'column')},
            },
        ),
    ]
