# Generated by Django 5.0.4 on 2024-10-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='student',
            field=models.ManyToManyField(related_name='rooms', to='accounts.student'),
        ),
    ]
