# Generated by Django 5.0.4 on 2024-09-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'room', 'verbose_name_plural': 'rooms'},
        ),
        migrations.AlterModelTable(
            name='room',
            table='room',
        ),
    ]
