# Generated by Django 5.0.4 on 2024-10-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('rooms', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='homeroom_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_classes', to='accounts.teacher'),
        ),
    ]
