# Generated by Django 5.0.4 on 2024-10-07 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0003_rename_room_name_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='accounts.student'),
        ),
    ]
