# Generated by Django 5.0.4 on 2024-10-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0004_alter_room_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='accounts.student'),
        ),
    ]
