# Generated by Django 5.0.4 on 2024-10-11 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='student',
        ),
        migrations.AddField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_student': True}, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='homeroom_teacher',
            field=models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
