# Generated by Django 5.0.4 on 2024-10-12 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0006_remove_room_student_room_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='homeroom_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_rooms', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to='accounts.student'),
        ),
    ]
