# Generated by Django 5.0.4 on 2024-10-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0007_alter_room_homeroom_teacher_alter_room_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(related_name='rooms', to='accounts.student'),
        ),
    ]
