# Generated by Django 5.0.4 on 2024-10-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_student_attendance_user'),
        ('rooms', '0005_alter_room_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Có mặt'), (2, 'Đi muộn'), (2, 'Vắng mặt')], null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='rooms.room'),
        ),
    ]
