# Generated by Django 5.0.4 on 2024-10-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'Có mặt'), (2, 'Đi muộn'), (3, 'Vắng mặt')], null=True),
        ),
    ]
