# Generated by Django 5.0.4 on 2024-09-26 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_alter_admin_options_alter_parent_options_and_more'),
        ('rooms', '0002_alter_room_options_alter_room_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_begin', models.DateField()),
                ('day_end', models.DateField(blank=True, null=True)),
                ('semester', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Thứ 2'), ('Tue', 'Thứ 3'), ('Wed', 'Thứ 4'), ('Thu', 'Thứ 5'), ('Fri', 'Thứ 6'), ('Sat', 'Thứ 7')], max_length=3)),
                ('subject', models.CharField(choices=[('Toan', 'Toán'), ('Van', 'Ngữ Văn'), ('Anh', 'Tiếng Anh'), ('KHTN_Hoa', 'Hoá'), ('KHTN Ly', 'Vật lý'), ('KHTN Sinh', 'Sinh học'), ('LSĐL Dia', 'Địa lý'), ('LSĐL Su', 'Lịch sử'), ('GDCD', 'GDCD'), ('TD', 'Thể dục'), ('My thuat', 'Mỹ thuật'), ('Am nhac', 'Âm nhạc'), ('Tin hoc', 'Tin học'), ('Cong Nghe', 'Công nghệ'), ('HDTN HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20)),
                ('period', models.IntegerField(choices=[(1, 'Tiết 1'), (2, 'Tiết 2'), (3, 'Tiết 3'), (4, 'Tiết 4'), (5, 'Tiết 5'), (6, 'Tiết 6'), (7, 'Tiết 7'), (8, 'Tiết 8'), (9, 'Tiết 9'), (10, 'Tiết 10')])),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='rooms.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.semester')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'db_table': 'Lesson',
            },
        ),
        migrations.CreateModel(
            name='StudyWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_weeks', to='adminpanel.semester')),
            ],
            options={
                'verbose_name': 'Study Week',
                'verbose_name_plural': 'Study Weeks',
                'db_table': 'study_week',
            },
        ),
    ]
