# Generated by Django 5.0.4 on 2024-10-06 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('rooms', '0003_rename_room_name_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester', models.IntegerField(primary_key=True, serialize=False)),
                ('day_begin', models.DateField()),
                ('number_of_weeks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='PlannedLesson',
            fields=[
                ('subject', models.CharField(choices=[('Toan', 'Toán'), ('Van', 'Ngữ Văn'), ('Anh', 'Tiếng Anh'), ('Hoa', 'Hoá'), ('Ly', 'Vật lý'), ('Sinh', 'Sinh học'), ('Dia', 'Địa lý'), ('Su', 'Lịch sử'), ('GDCD', 'GDCD'), ('TD', 'Thể dục'), ('MT', 'Mỹ thuật'), ('AN', 'Âm nhạc'), ('TH', 'Tin học'), ('CN', 'Công nghệ'), ('HDTN-HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20)),
                ('lesson_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name_lesson', models.CharField(max_length=100)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.semester')),
            ],
            options={
                'verbose_name': 'Planned Lesson',
                'verbose_name_plural': 'Planned Lessons',
                'unique_together': {('subject', 'semester', 'lesson_number')},
            },
        ),
        migrations.CreateModel(
            name='StudyWeek',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('week_number', models.IntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_weeks', to='adminpanel.semester')),
            ],
            options={
                'verbose_name': 'Study Week',
                'verbose_name_plural': 'Study Weeks',
                'db_table': 'study_week',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluate', models.IntegerField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='rooms.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='adminpanel.period')),
                ('planned_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.plannedlesson')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='adminpanel.semester')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'unique_together': {('day', 'room', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Toan', 'Toán'), ('Van', 'Ngữ Văn'), ('Anh', 'Tiếng Anh'), ('Hoa', 'Hoá'), ('Ly', 'Vật lý'), ('Sinh', 'Sinh học'), ('Dia', 'Địa lý'), ('Su', 'Lịch sử'), ('GDCD', 'GDCD'), ('TD', 'Thể dục'), ('MT', 'Mỹ thuật'), ('AN', 'Âm nhạc'), ('TH', 'Tin học'), ('CN', 'Công nghệ'), ('HDTN-HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20)),
                ('score_type', models.CharField(choices=[('15p', 'Điểm 15p'), ('1Tiet', 'Điểm 1 tiết'), ('GiuaKy', 'Điểm giữa kỳ'), ('CuoiKy', 'Điểm cuối kỳ')], max_length=10)),
                ('grade', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.student')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.semester')),
            ],
            options={
                'verbose_name': 'Điểm',
                'verbose_name_plural': 'grades',
                'db_table': 'grades',
                'unique_together': {('student', 'subject', 'semester', 'score_type')},
            },
        ),
    ]
