# Generated by Django 5.0.4 on 2024-09-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='study_week',
        ),
    ]
