# Generated by Django 5.0.4 on 2024-10-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='subject',
            field=models.CharField(choices=[('TOAN', 'Toán'), ('VAN', 'Ngữ Văn'), ('ANH', 'Tiếng Anh'), ('KHTN_HOA', 'Hoá'), ('KHTN_LY', 'Vật lý'), ('KHTN_SINH', 'Sinh học'), ('KHXH_DIA', 'Địa lý'), ('KHXH_SU', 'Lịch sử'), ('KHXH_GDCD', 'GDCD'), ('TD', 'Thể dục'), ('MT', 'Mỹ thuật'), ('AN', 'Âm nhạc'), ('TH', 'Tin học'), ('CN', 'Công nghệ'), ('HDTN-HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='subject',
            field=models.CharField(choices=[('TOAN', 'Toán'), ('VAN', 'Ngữ Văn'), ('ANH', 'Tiếng Anh'), ('KHTN_HOA', 'Hoá'), ('KHTN_LY', 'Vật lý'), ('KHTN_SINH', 'Sinh học'), ('KHXH_DIA', 'Địa lý'), ('KHXH_SU', 'Lịch sử'), ('KHXH_GDCD', 'GDCD'), ('TD', 'Thể dục'), ('MT', 'Mỹ thuật'), ('AN', 'Âm nhạc'), ('TH', 'Tin học'), ('CN', 'Công nghệ'), ('HDTN-HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='plannedlesson',
            name='subject',
            field=models.CharField(choices=[('TOAN', 'Toán'), ('VAN', 'Ngữ Văn'), ('ANH', 'Tiếng Anh'), ('KHTN_HOA', 'Hoá'), ('KHTN_LY', 'Vật lý'), ('KHTN_SINH', 'Sinh học'), ('KHXH_DIA', 'Địa lý'), ('KHXH_SU', 'Lịch sử'), ('KHXH_GDCD', 'GDCD'), ('TD', 'Thể dục'), ('MT', 'Mỹ thuật'), ('AN', 'Âm nhạc'), ('TH', 'Tin học'), ('CN', 'Công nghệ'), ('HDTN-HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20),
        ),
    ]
