# Generated by Django 5.0.4 on 2024-10-06 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grades',
            unique_together={('student', 'subject', 'semester', 'score_type')},
        ),
    ]
