# Generated by Django 5.0.4 on 2024-10-27 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('adminpanel', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='adminpanel.period'),
        ),
        migrations.AddField(
            model_name='plannedlesson',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_lessons', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='plannedlesson',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_lessons', to='adminpanel.semester'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='adminpanel.semester'),
        ),
        migrations.AddField(
            model_name='grades',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.semester'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.room'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='adminpanel.semester'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='plannedlesson',
            unique_together={('subject', 'semester', 'lesson_number', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('semester', 'room', 'subject', 'day', 'period')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('room', 'subject')},
        ),
    ]
