# Generated by Django 5.0.4 on 2024-10-18 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grades',
            name='score_type',
            field=models.CharField(choices=[('TX', 'Đánh giá thường xuyên'), ('GK', 'Điểm giữa kỳ'), ('CK', 'Điểm cuối kỳ')], max_length=10),
        ),
    ]
