# Generated by Django 5.0.4 on 2024-10-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_grades_subject_alter_lesson_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudyWeek',
        ),
    ]
