# Generated by Django 5.0.4 on 2024-10-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_delete_studyweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='grades',
            name='score_type',
            field=models.CharField(choices=[('TX', 'Đánh giá thường xuyên'), ('GiuaKy', 'Điểm giữa kỳ'), ('CuoiKy', 'Điểm cuối kỳ')], max_length=10),
        ),
    ]
