# Generated by Django 5.0.4 on 2024-10-17 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('adminpanel', '0004_rename_semester_semester_name_and_more'),
        ('rooms', '0008_alter_room_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubjectTeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('TOAN', 'Toán'), ('VAN', 'Ngữ Văn'), ('ANH', 'Tiếng Anh'), ('KHTN_HOA', 'Hoá'), ('KHTN_LY', 'Vật lý'), ('KHTN_SINH', 'Sinh học'), ('KHXH_DIA', 'Địa lý'), ('KHXH_SU', 'Lịch sử'), ('KHXH_GDCD', 'GDCD'), ('TD', 'Thể dục'), ('MT', 'Mỹ thuật'), ('AN', 'Âm nhạc'), ('TH', 'Tin học'), ('CN', 'Công nghệ'), ('HDTN-HN', 'Hoạt động trại nghiệm, hướng nghiệp')], max_length=20)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_teacher_assignments', to='rooms.room')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='accounts.teacher')),
            ],
            options={
                'unique_together': {('room', 'subject')},
            },
        ),
    ]
